config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  # Protect against timing attacks:
  # - See https://codahale.com/a-lesson-in-timing-attacks/
  # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
  # - Use & (do not use &&) so that it doesn't short circuit.
  # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
end 
Rails.application.routes.draw do
  #get 'articles', to: 'articles#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles do
    resources :comments
  end

  mount Sidekiq::Web => "/sidekiq"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible 
    has_many :comments, dependent: :destroy
    validates :title, presence: {message: "Es obligatorio el titulo!"}
    validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible 
  belongs_to :article

end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
          where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sessions, dependent: :destroy
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  before_validation :normalice_email
  validates :password, presence: true, length: { minimum: 8 }, format: { with: /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])/ }
  after_create_commit :send_verification_email
  has_secure_password 

  def normalice_email
    self.email = email.downcase.strip
  end

  def send_verification_email
    UserMailer.with(user: self).verification_email.deliver_later
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate
    def authenticate
        if session = Session.find_by(id: cookies.signed[:session_token])
            @current_user = session.user
            @current_session = session
        else
            redirect_to new_session_url
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_url, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_url(@article)
    end

    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_url(@article), status: :see_other
    end

    def edit
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
    end
  
    def update
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      if @comment.update(comment_params)
        redirect_to @article
      else
        render :edit, status: :unprocessable_entity
      end
    end



    private
      def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authenticate, only: [:new, :create]
    def new
        @user = User.new
    end

    def create
        @user = User.find_by(email: params[:email].downcase)
        if @user && @user.authenticate(params[:password])
            session = @user.sessions.create(user_agent: request.user_agent, ip_address: request.remote_ip)
            cookies.signed.permanent[:session_token] = {value: session.id, httponly: true}
            redirect_to root_url, notice: "Logged in!" 
        else
            @sign_in_error = true
            render :new, status: :unauthorized
        end
    end

    def destroy
        session = @current_user.sessions.find(params[:id])
        session.destroy
        redirect_to root_url, notice: "Logged out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authenticate, only: [:new, :create]
    def new
        @user = User.new
    end


    def create
        @user = User.new(user_params)
    
        if @user.save
          session = @user.sessions.create(user_agent: request.user_agent, ip_address: request.remote_ip)
          cookies.signed.permanent[:session_token] = {value: session.id, httponly: true}
          redirect_to root_url, notice: "Thank you for signing up!"
        else
          render :new, status: :unprocessable_entity
        end
    end

    private
        def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

<%= link_to "Back", article_path %>

app/views/articles/index.html.erb
<body>
  <div class="overflow-hidden rounded-lg border border-gray-200 shadow-md m-5">
    <h1>Articles</h1>
  <div data-controller="greeting hello">
    <input type="text" data-greeting-target="name">
    <button data-action="click->greeting#greet click->hello#showAlert">Chears</button>
    <span data-greeting-target="output"></span>
    <br/>
    <button data-action="click->hello#showAlert">Mostrar Alerta</button>
  </div>
  <br>Our blog has <%= Article.public_count %> articles and counting!
  <div data-controller="hello">
    <button data-action="click->hello#showAlert">Mostrar alerta</button>
  </div>
  <div>
  <ul>
    <% @articles.each do |article| %>
      <% unless article.archived? %>
      <div class="divide-y divide-gray-100 border-t border-gray-100">
        <div><li>
          <%= link_to article.title, article %>
        </li></div>
      <% end %>
      </div>
    <% end %>
  </ul>
  </div>

    <%= link_to "New Article", new_article_path %>
  </div>
</body>


<!-- component 
<section class="text-gray-600 body-font bg-gray-50 h-screen flex justify-center items-center">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap -m-4 text-center">
      <div class="p-4 sm:w-1/2 lg:w-1/3 w-full hover:scale-105 duration-500">
        <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
          <div>
            <h2 class="text-gray-900 text-lg font-bold">Total Ballance</h2>
            <h3 class="mt-2 text-xl font-bold text-yellow-500 text-left">+ 150.000 ₭</h3>
            <p class="text-sm font-semibold text-gray-400">Last Transaction</p>
            <button class="text-sm mt-6 px-4 py-2 bg-yellow-400 text-white rounded-lg  tracking-wider hover:bg-yellow-300 outline-none">Add to cart</button>
          </div>
          <div
            class="bg-gradient-to-tr from-yellow-500 to-yellow-400 w-32 h-32  rounded-full shadow-2xl shadow-yellow-400 border-white  border-dashed border-2  flex justify-center items-center ">
            <div>
              <h1 class="text-white text-2xl">Basic</h1>
            </div>
          </div>
        </div>

      </div>
      <div class="p-4 sm:w-1/2 lg:w-1/3 w-full hover:scale-105 duration-500">
        <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
          <div>
            <h2 class="text-gray-900 text-lg font-bold">Total Ballance</h2>
            <h3 class="mt-2 text-xl font-bold text-orange-500 text-left">+ 150.000 ₭</h3>
            <p class="text-sm font-semibold text-gray-400">Last Transaction</p>
            <button class="text-sm mt-6 px-4 py-2 bg-orange-400  text-white rounded-lg  tracking-wider hover:bg-orange-500 outline-none">Add to cart</button>
          </div>
          <div
            class="bg-gradient-to-tr from-orange-500 to-orange-400 w-32 h-32  rounded-full shadow-2xl shadow-orange-400 border-white  border-dashed border-2  flex justify-center items-center ">
            <div>
              <h1 class="text-white text-2xl">Basic</h1>
            </div>
          </div>
        </div>

      </div>
      <div class="p-4 sm:w-1/2 lg:w-1/3 w-full hover:scale-105 duration-500">
        <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
          <div>
            <h2 class="text-gray-900 text-lg font-bold">Total Ballance</h2>
            <h3 class="mt-2 text-xl font-bold text-red-500 text-left">+ 150.000 ₭</h3>
            <p class="text-sm font-semibold text-gray-400">Last Transaction</p>
            <button class="text-sm mt-6 px-4 py-2 bg-red-400  text-white rounded-lg  tracking-wider hover:bg-red-500 outline-none">Add to cart</button>
          </div>
          <div
            class="bg-gradient-to-tr from-red-500 to-red-400 w-32 h-32  rounded-full shadow-2xl shadow-red-400 border-white  border-dashed border-2  flex justify-center items-center ">
            <div>
              <h1 class="text-white text-2xl">Basic</h1>
            </div>
          </div>
        </div>

      </div>

      <div class="p-4 sm:w-1/2 lg:w-1/3 w-full hover:scale-105 duration-500">
        <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
          <div>
            <h2 class="text-gray-900 text-lg font-bold">Total Ballance</h2>
            <h3 class="mt-2 text-xl font-bold text-green-500 text-left">+ 150.000 ₭</h3>
            <p class="text-sm font-semibold text-gray-400">Last Transaction</p>
            <button class="text-sm mt-6 px-4 py-2 bg-green-400  text-white rounded-lg  tracking-wider hover:bg-green-500 outline-none">Add to cart</button>
          </div>
          <div
            class="bg-gradient-to-tr from-green-500 to-green-500 w-32 h-32  rounded-full shadow-2xl shadow-green-400 border-white  border-dashed border-2  flex justify-center items-center ">
            <div>
              <h1 class="text-white text-2xl">Basic</h1>
            </div>
          </div>
        </div>

      </div>
            <div class="p-4 sm:w-1/2 lg:w-1/3 w-full hover:scale-105 duration-500">
        <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
          <div>
            <h2 class="text-gray-900 text-lg font-bold">Total Ballance</h2>
            <h3 class="mt-2 text-xl font-bold text-cyan-500 text-left">+ 150.000 ₭</h3>
            <p class="text-sm font-semibold text-gray-400">Last Transaction</p>
            <button class="text-sm mt-6 px-4 py-2 bg-cyan-400  text-white rounded-lg  tracking-wider hover:bg-cyan-500 outline-none">Add to cart</button>
          </div>
          <div
            class="bg-gradient-to-tr from-cyan-500 to-cyan-400 w-32 h-32  rounded-full shadow-2xl shadow-cyan-400 border-white  border-dashed border-2  flex justify-center items-center ">
            <div>
              <h1 class="text-white text-2xl">Basic</h1>
            </div>
          </div>
        </div>

      </div>
      <div class="p-4 sm:w-1/2 lg:w-1/3 w-full hover:scale-105 duration-500">
        <div class=" flex items-center  justify-between p-4  rounded-lg bg-white shadow-indigo-50 shadow-md">
          <div>
            <h2 class="text-gray-900 text-lg font-bold">Total Ballance</h2>
            <h3 class="mt-2 text-xl font-bold text-indigo-500 text-left">+ 150.000 ₭</h3>
            <p class="text-sm font-semibold text-gray-400">Last Transaction</p>
            <button class="text-sm mt-6 px-4 py-2 bg-indigo-400 text-white rounded-lg  tracking-wider hover:bg-indigo-500 outline-none">Add to cart</button>
          </div>
          <div
            class="bg-gradient-to-tr from-indigo-500 to-indigo-400 w-32 h-32  rounded-full shadow-2xl shadow-[#304FFE] border-white  border-dashed border-2  flex justify-center items-center ">
            <div>
              <h1 class="text-white text-2xl">Basic</h1>
            </div>
          </div>
        </div>

      </div>
    </div>
</section>
-->

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div><h1><%= @article.title %></h1><br>
<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit article", edit_article_path %></li>
  <li><%= link_to "Back", articles_path %></li>
  <li data-controller="dialog">
      <button data-action="dialog#superShow">Destroy</button>
      <dialog data-dialog-target="dialog">Estas seguro de realizar esta acción?<%= button_to "Destroy", article_path(@article), method: :delete %><button data-action="dialog#close">Cerrar</button></dialog>
  </li>
</ul>
</div>
<div>
<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <%= turbo_frame_tag comment do %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
<% end %>
</div>
<div>
<h2>Add a comment:</h2>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <%= render 'comments/form'%>
<% end %>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= button_to "Destroy Comment", [comment.article, comment], method: :delete, data: {
                  turbo_confirm: "Are you sure?", turbo_frame: '_top'
                } %>
  </p>
  <%= link_to "Edit comment", edit_article_comment_path(comment.article, comment) %>
<% end %>

app/views/comments/_editForm.html.erb
<%= form_with model: [ @article, @comment] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
  <p>
    <%= form.submit %>
    <%= link_to "Cancelar", article_path(@article) %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
    <%= render 'editForm', comment: @comment %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cruza</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <nav class="relative select-none bg-grey lg:flex lg:items-stretch w-full">
    <div class="flex flex-no-shrink items-stretch h-12">
      <a href="#" class="flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-grey-dark">Cruza</a>
      <a href="#" class="flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-grey-dark">Css</a>
      <button class="block lg:hidden cursor-pointer ml-auto relative w-12 h-12 p-4">
        <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 8.586L2.929 1.515 1.515 2.929 8.586 10l-7.071 7.071 1.414 1.414L10 11.414l7.071 7.071 1.414-1.414L11.414 10l7.071-7.071-1.414-1.414L10 8.586z"/></svg>
      </button>
    </div>
    <div class="lg:flex lg:items-stretch lg:flex-no-shrink lg:flex-grow">
      <div class="lg:flex lg:items-stretch lg:justify-end ml-auto">
        <div class="flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-grey-dark">
          <%= link_to "Articles", articles_path %>
        </div>
        <a href="#" class="flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-grey-dark">Articles</a>
        <%if @current_user%>
        <div class="flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-grey-dark">
          <%= @current_user.email%>
        </div>
        <div class="flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-grey-dark">
          <%= button_to "Sign out", session_path(@current_session), method: :delete%>
        </div>
        <%else%>
        <div class="flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-grey-dark">
          <%= link_to "Sign in", new_session_path %>
        </div>
        <div class="flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-grey-dark">
          <%= link_to "Sign up", new_user_path %>
        </div>
        <% end %>
      </div>
    </div>
  </nav>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with model: @user do |form| %>
    <div>
        <%= form.label :email %><br>
        <%= form.email_field :email, required: true %>
        <% @user.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :password %><br>
        <%= form.password_field :password, required: true %>
        <% @user.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :password %><br>
        <%= form.password_field :password_confirmation, required: true %>
        <% @user.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit "Registrarse" %>
    </div>
<% end %>